# Introduction to R 

This is an introductory module in which we will learn the basics of R/Rstudio from installation to loading your first data file into R. R is a high level language that was developed by statisticians and was meant for statisticians. The two statisticians who came up with the language are Rose Ihaka and Robert Gentleman from the University of Aukland Australia. 

Since its implementation it has gained popularity over time by find use cases in new emerging fields like Data Science and lately in the Pharmaceutical industry now sharing almost an equal place with SAS (Statistical Analysis System) which has been the standard programming language in the Pharma industry for a very long time.

What makes R powerful is the idea of packages which is simply a collection of functions and data that have been packaged in a way that makes it easy for use and share with the large community. You will learn how to install and load packages in this module. For those who will advance in the series, you might as well learn how to create them as well.

## LEARNING OUTCOMES/OBJECTIVES

**i) Installation for both R and Rstudio**

Install R software @ https://cran.r-project.org/bin/windows/base/

Install Rstudio @ https://posit.co/download/rstudio-desktop/

**ii) Introduction to Rstudio Interface**

Familiarize with the Rstudio user interface which we will use heavily. There are other editors that you can use like VS code, but Rstudio is widely used in the industry.

**iii) Data types**

We need to understand basic data types before delving into complicated data structures. This will serve as a foundation to our future analysis of data in various contexts.

**iv) R packages**

A brief introduction to what packages are, how to install and load them into the system. (we will not cover how to make your own package at this stage yet)

**V) Data Import from various sources**

How do you get your data into the R system. There are various ways of achieving this. We shall sample few methods.


**N/B: Please install both R and Rstudio before our class.**

*Useful resource*

https://rstudio-education.github.io/hopr/

